In [1]:
# importing sys
import sys
  
# adding srcpy to the system path
sys.path.insert(0, "/Users/charles/Desktop/DSAI/6_DataScience/project/DSP/zr1/src/srcpy")

import data_proc

# Auto reload: watch a directory for changed files and restarts a process when the change is detected
%load_ext autoreload
%autoreload 2

In [2]:
import random
import numpy as np
import pandas as pd
pd.options.display.max_columns = None
pd.options.mode.chained_assignment = None
pd.options.display.float_format

import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.pylab as pylab
mpl.style.use("ggplot")
pylab.rcParams["figure.figsize"] = 8 , 6

import seaborn as sns
sns.set_style("white")

from pandas_profiling import ProfileReport

In [3]:
df = data_proc.load_training_data("/Users/charles/Desktop/DSAI/6_DataScience/project/DSP/20221/data/zillow.csv")
df = df.drop(['Unnamed: 0', "type", "rent_zestimate", "zestimate", "broker_name", "full_bathrooms"], axis=1)
df.head()

,price,status,has_add_attributions,city,state,latitude,longitude,bathrooms,bedrooms,living_area,lot_area,tax_assessed_value,num_fireplaces,parking,covered_spaces,garage_spaces,total_spaces,lot_features,subtype,architectural_style,year_built,sewer_info,water_info,appliances,heating,cooling,stories,materials,roof,foundation,interior_features,compensation
0,274000,House for sale,True,South Ozone Park,NY,40.675730,-73.822350,1,3,1556,2400.0,0,none,Garage - Detached,1.750,1.595,1.945,none,none,none,1930.0,none,none,none,none,none,0.0,none,none,none,none,none
1,270000,House for sale,True,Jamaica,NY,40.670036,-73.780450,2,4,1920,3998.0,678000,none,none,1.660,1.535,2.160,none,none,none,1950.0,none,none,microwave,none,none,0.0,none,none,none,none,none
2,899000,House for sale,True,Staten Island,NY,40.524227,-74.215790,3,3,2532,6903.0,637000,none,Detache,1.935,2.000,2.000,none,Single Family - Detached,Colonial,1899.0,Public Sewer,none,dishwasher,hot water,Units,2.0,none,none,none,none,none
3,1390000,House for sale,True,Flushing,NY,40.721615,-73.820755,4,4,1915,2697.0,894000,none,none,1.695,1.655,3.915,none,none,none,1945.0,none,none,dryer,none,none,0.0,none,none,none,none,none
4,1390000,House for sale,True,Flushing,NY,40.721615,-73.820755,4,4,1915,2697.0,0,none,Shared Drivewa,1.540,1.000,3.705,Near Public Transit,Single Family Residence,Semi Detached,1945.0,Public Sewer,Public,none,natural gas,Wall Unit(s),3.0,frame,none,none,Eat-in Kitche,none

In [4]:
print("Number of house: {}".format(len(df)))

Number of house: 13339