In [131]:
# importing sys
import sys
  
# adding srcpy to the system path
sys.path.insert(0, "/Users/charles/Desktop/DSAI/6_DataScience/project/DSP/20221/srcpy")

import data_proc, feature_proc

# Auto reload: watch a directory for changed files and restarts a process when the change is detected
%load_ext autoreload
%autoreload 2

import random
import numpy as np
import pandas as pd
pd.options.display.max_columns = None
pd.options.mode.chained_assignment = None
pd.options.display.float_format

import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.pylab as pylab
mpl.style.use("ggplot")
pylab.rcParams["figure.figsize"] = 8 , 6

import seaborn as sns
sns.set_style("white")

from pandas_profiling import ProfileReport

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [132]:
# Load training data with some drops
df= data_proc.load_training_data("/Users/charles/Desktop/DSAI/6_DataScience/project/DSP/20221/data/zillow.csv")
# convert TF to Float
df = convert_true_to_float(df, "has_add_attributions")
data_proc.rename_columns(df)
df = data_proc.del_dup(df)
df = data_proc.encode_cat(df)
df.head()

,price,status,add_attr,city,state,lat,long,bath,bed,living,lot_a,tax_assessed,fireplace,parking,covered,garage,total_spaces,lot_f,subtype,architectural,year,sewer,water,app,heating,cooling,stories,materials,roof,foundation,interior,compensation
0,274000,4,1.0,143,8,40.675730,-73.822350,1,3,1556,2400.0,0,53,141,1.750,1.595,1.945,359,26,386,1930.0,99,71,87,57,114,0.0,94,284,22,445,364
1,270000,4,1.0,73,8,40.670036,-73.780450,2,4,1920,3998.0,678000,53,280,1.660,1.535,2.160,359,26,386,1950.0,99,71,83,57,114,0.0,94,284,22,445,364
2,899000,4,1.0,146,8,40.524227,-74.215790,3,3,2532,6903.0,637000,53,91,1.935,2.000,2.000,359,19,70,1899.0,60,71,30,49,95,2.0,94,284,22,445,364
3,1390000,4,1.0,46,8,40.721615,-73.820755,4,4,1915,2697.0,894000,53,280,1.695,1.655,3.915,359,26,386,1945.0,99,71,34,57,114,0.0,94,284,22,445,364
5,1380000,4,1.0,17,8,40.604470,-73.943960,4,3,1800,2000.0,0,53,258,1.700,1.000,2.160,214,22,2,1930.0,60,54,30,55,98,2.0,20,284,22,161,364